### ISSUE TITLE
User Story 1: Welcome page

### ISSUE THREAD

**Issue by s-kond** [s-kond/userstories-capstone#2]
## Value Proposition
As a user, 
I want to see a welcome screen,
so that I know that the app started successfully.

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/79710919/197547193-42bbbc55-18f8-4c13-a5be-fe3f9f1365c9.png)

## Acceptance criteria
- [x] you can see the name of the app 
- [x] you can read a welcome-message

## Tasks
- [x] create new react project
- [x] remove unnecessary data
- [x] add h1 with app-title to app.js
- [x] add p with welcome message to app.js
- [x] install styled-components
- [x] add fonts and basic styling (h1: Cookies, p: Montserrat, background: #DCEDC1)

## Size
small

**Comment by mpagels** [comment]
Never put something in a user story, that has no value for a user. A button that does nothing, has no value. The user clicks the button and nothing happens and is confused. You could use this story as a second story or as a story after you have created a cooking list and display the data here and the + button can link to the add form.
